[package]
name = "ma-tui"
version = "0.110.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ma-core.workspace = true
ma-provider.workspace = true
ma-coordinator.workspace = true
ma-runtime.workspace = true
anyhow.workspace = true
crossterm.workspace = true
futures.workspace = true
ratatui.workspace = true
tokio.workspace = true
pulldown-cmark.workspace = true
url.workspace = true

[dev-dependencies]
tempfile.workspace = true
