[package]
name = "ma-runtime"
version = "0.110.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ma-core.workspace = true
ma-journal.workspace = true
ma-coordinator.workspace = true
ma-context.workspace = true
ma-provider.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
