pub const DEFAULT_CONTEXT_TOKENS: u64 = 128_000;
pub const DEFAULT_PROVIDER_TIMEOUT_SECS: u64 = 300;
pub const DEFAULT_BASE_URL: &str = "https://api.openai.com/v1";
pub const PROVIDER_SETTINGS_FILE: &str = "provider.json";
pub const PROVIDER_KIND_OPENAI: &str = "openai-compatible";

pub const ENV_CONTEXT_TOKEN_KEYS: &[&str] = &[
    "OPENAI_CONTEXT_TOKENS",
    "PENTESTING_CONTEXT_TOKENS",
    "PENTESTING_MAX_CONTEXT_TOKENS",
    "OPENAI_MAX_CONTEXT_TOKENS",
    "CONTEXT_TOKENS",
    "MAX_CONTEXT_TOKENS",
];

pub const ENV_MAX_OUTPUT_TOKEN_KEYS: &[&str] = &[
    "OPENAI_MAX_TOKENS",
    "OPENAI_MAX_OUTPUT_TOKENS",
    "OPENAI_OUTPUT_MAX_TOKENS",
    "OPENAI_MAX_COMPLETION_TOKENS",
    "PENTESTING_MAX_TOKENS",
    "PENTESTING_MAX_OUTPUT_TOKENS",
    "PENTESTING_OUTPUT_MAX_TOKENS",
    "MAX_OUTPUT_TOKENS",
    "OUTPUT_MAX_TOKENS",
];
